# Generated by Django 3.0.4 on 2020-03-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1User', models.TextField()),
                ('player2User', models.TextField()),
                ('player1HP', models.IntegerField()),
                ('player2HP', models.IntegerField()),
            ],
        ),
    ]
