# Generated by Django 3.0.4 on 2020-03-24 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameRoom',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='chat.Rooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player1Char',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2Char',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1HP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2HP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2User',
            field=models.TextField(blank=True, null=True),
        ),
    ]
