# Generated by Django 3.0.4 on 2020-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200324_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1Action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2Action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
