# Generated by Django 3.0.4 on 2020-04-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200410_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameOver',
            field=models.BooleanField(default=False),
        ),
    ]
